version: "2"

services:
 web1:
  build: "./app1"
  ports:
   - "5050:5000"
  depends_on:
   - redis

 web2:
  build: "./app2"
  ports:
   - "5051:5000"
  depends_on:
   - redis

 processor:
  build: "./processor"
  depends_on:
   - redis

 redis:
  image: "redis:alpine"
